### ISSUE TITLE
Cannot install the deb package

### ISSUE THREAD

**Issue by yngvark** [sobolevn/git-secret#45] opened 2016-08-19 07:29 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. Run the installation for the deb package:
```
echo "deb https://dl.bintray.com/sobolevn/deb git-secret stable" | sudo tee -a /etc/apt/sources.list
sudo apt-get install git-secret
```

What happens?
-------------
```
$ sudo apt-get install git-secret
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package git-secret

```

What were you expecting to happen?
----------------------------------
git-secret to be installed

Any logs, error output, etc?
----------------------------
When running `sudo apt-get update`, I get the following:
`E: Failed to fetch https://dl.bintray.com/sobolevn/deb/dists/git-secret/stable/binary-amd64/Packages  404  Not Found`

Full log: https://ghostbin.com/paste/okrvy

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating system:** Ubuntu 16.04 LTS
Linux x 4.4.8-040408-generic #201604200335 SMP Wed Apr 20 07:37:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` version:** …

**Shell type and version:** …

**Comment by sobolevn** [comment] 2016-08-19 08:07
Thanks for the report. Will solve.

**Comment by sobolevn** [comment] 2016-08-20 10:33
Hm, I guess `bintray` is broken. I have created a support-request.

For now, please, use different installation types.

**Comment by sobolevn** [comment] 2016-08-20 12:54
Wow, that was a hard one.

Thank you for your report. The problem is fixed now.
I am going to write new docs and upload them pretty soon (today or tomorrow).

**Comment by sobolevn** [comment] 2016-08-21 13:40
@yngvark see if this helps https://sobolevn.github.io/git-secret/#installation

Please take note, that `deb` location has changed. You might need to remove the old one.

**Comment by yngvark** [comment] 2016-08-22 06:42
Now the installation worked fine in a ubuntu docker image, so it seems to be fixed. Thanks for fast reply and fix.

**Closed** 2016-08-22 06:42 UTC
