### ISSUE TITLE
PR #553 Introduced Issue Where 2 Keys w/ Same Email Cannot Be Removed

### ISSUE THREAD

**Issue by StephenMP** [sobolevn/git-secret#638] opened 2021-01-15 20:46 UTC
**Note**: This was introduced here: https://github.com/sobolevn/git-secret/pull/553/files#diff-c42b4adec468269525eb8eec22edb6ed562ecf49970ffb6a09b9e0ab815bfe7fR619

What are the steps to reproduce this issue?
-------------------------------------------
1. Create a gpg key
2. Do a `git secret tell` for above public key using the email
3. Manually remove gpg key from system
4. Create a new gpg key using same email as in step #1
5. Do a `git secret tell` for new gpg key w/ same email
6. Do a `git secret whoknows` and verify that the email is added twice
7. Do a `git secret killperson <email>` with the email used to create both gpg keys

What happens?
-------------
git secret aborts saying that 2 emails have been found

What were you expecting to happen?
----------------------------------
You should be able to remove the keys even if the email appears multiple times

Any logs, error output, etc?
----------------------------
git-secret: abort: 2 keys found in gpg keyring for: your.email@whatever.net

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating system:** Darwin MacBook-Pro 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**`git-secret` path:** `/usr/local/bin/git-secret`

**`git-secret` version:** 0.3.3

**`git` version:** 2.30.0

**Shell type and version:** zsh 5.7.1 (x86_64-apple-darwin19.0)

**`gpg` version:** 2.2.27

**Comment by shirakaba** [comment] 2021-07-01 10:55
@StephenMP Thanks for addressing this issue. Until this PR gets merged, I don't suppose there's a way for me to manually (e.g. via standard shell commands) force the removal of a duplicate person in the keyring? I'm on macOS 12.0 Beta, with `git` version 2.28.0 and of course have both `zsh` and `bash` available.

**Comment by joshrabinowitz** [comment] 2021-07-01 13:54
@shirakaba @StephenMP @sobolevn 

Just a heads up - git-secret creates a gpg keyring (using gpg) in your repo's `.git-secret` directory. It should be possible (although discouraged!) to use gpg to manipulate this key ring directly manually and resolve this issue.

I've created issue #699 to document more about the keyring used by the git-secret repo, and I've also commented on #638. Thank you for your patience, and let us know if you have any updates.

**Closed** 2022-01-17 14:43 UTC

**Comment by bennycode** [comment] 2022-04-25 16:23
I can confirm that the issue is fixed in "git secret 0.5.0-alpha1". I had an email 4x in the list (`git secret whoknows`) and removed all keys by calling `git secret removeperson <email>` 4x. Afterwards, I added the latest key of that person and executed `git secret tell` to have a clean list of people who know the secrets.
