### ISSUE TITLE
git secret tell using USER_ID = key id, key fingerprint, email

### ISSUE THREAD

**Issue by ieugen** [sobolevn/git-secret#512] opened 2019-08-18 08:58 UTC
Hello, 

I have multiple gpg keys with the same email address - for different use cases.
When I git secret tell, it adds both of them. I do not want that - I think it is a bug.
Second, git secret hide/reveal fails to pick the right key - IMO. I did not manage to use git secret when I have both keys.

It would be great to be able to specify a key bi it's ID or email, etc both when adding and removing.

p.s. It looks like the project is getting a lot of features. I don't have a lot of experience with bash scripting but I imagine it is not the best tool to write complex software.

Regards,
Eugen

**Comment by joshrabinowitz** [comment] 2019-08-18 12:20
This is a duplicate of #268

**Closed by joshrabinowitz** 2019-08-18 12:20 UTC

**Comment by joshrabinowitz** [comment] 2020-03-04 14:28
This is also similar to #552
