### ISSUE TITLE
routine _add_ignored_file changed from echo to printf - forgot to include \n (newline).

### ISSUE THREAD

**Issue by bunkiedc** [sobolevn/git-secret#651] opened 2021-03-15 18:44 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. …git secret add filename
2. …
3. …

What happens?
-------------
…file names in .gitignore are all put back to back on a single line... ie no cR/LF

What were you expecting to happen?
----------------------------------
…Each file should end up on a single line

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
The echo command from 0.3.2 
 393   echo "$filename" >> "$full_path"

was substituted for a printf statement in 0.3.3
  398   printf '%q' "$filename" >> "$full_path"

but neglected to include a newline.
The line should read
  398   printf '%q\n' "$filename" >> "$full_path"

as echo automatically adds a newline, whereas printf does not.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
Linux hostname 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**`git-secret` path:** (`which git-secret`) …

**`git-secret` version:** (`git secret --version`) …
0.3.3
**`git` version:** (`git --version`) …
git version 2.17.1
**Shell type and version:** (`$SHELL --version`) …
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
**`gpg` version:** (`gpg --version`) …
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1

**Comment by joshrabinowitz** [comment] 2021-03-15 21:21
hello @bunkiedc and thank you for this bug report.

This is a duplicate of #643, and @pedroos has worked up a fix in PR #645

Would it be possible for you to test using PR #645 and confirm that this fixes the problem for you?

If so I'll go ahead and merge that PR in and close these two issues.

**Comment by bunkiedc** [comment] 2021-03-15 22:53
Hi Josh,The patch that @pedroos posted in #643 is exactly the same that I didin my version here, which works great.  I've tried it on two different machines.


-----Original Message-----

**Closed** 2021-06-26 13:25 UTC
