### ISSUE TITLE
Foreign Characters in Filenames

### ISSUE THREAD

**Issue by paulpall** [sobolevn/git-secret#980] opened 2023-02-14 12:17 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a secret file with a UTF-8 character in the filename. For example: `Võtmed.py`.
2. `git secret init`
3. `git secret tell -m`
4. `git secret add Võtmed.py`

What happens?
-------------
`git-secret: abort: file not found: Võtmed.py`

What were you expecting to happen?
----------------------------------
```
git-secret: file not in .gitignore, adding: Votmed.py
git-secret: 1 item(s) added.
```

Any logs, error output, etc?
----------------------------
`git-secret: abort: file not found: Võtmed.py`
verbose mode doesn't seem to work on my git secret.

Any other comments?
-------------------
I'm not sure if it's caused just by this character or also happens with other common European characters like `ä`,`ö`,`ü`,etc...

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
Darwin Pauli-MacBook-Pro-4.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64

**`git-secret` path:** (`which git-secret`) …
/usr/local/bin/git-secret

**`git-secret` version:** (`git secret --version`) …
0.5.0

**`git` version:** (`git --version`) …
git version 2.24.3 (Apple Git-128)

**Shell type and version:** (`$SHELL --version`) …
zsh 5.8.1 (x86_64-apple-darwin22.0)

**`gpg` version:** (`gpg --version`) …
gpg (GnuPG) 2.4.0
libgcrypt 1.10.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/paul/.gnupg
Toetatud algoritmid:
Avalik võti: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Šiffer: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Räsi: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Pakkimine: Pakkimata, ZIP, ZLIB, BZIP2

**Comment by joshrabinowitz** [comment] 2023-02-27 13:27
This is a dupe of #642 and #702, closing

**Closed by joshrabinowitz** 2023-02-27 13:27 UTC
