### ISSUE TITLE
Issue with multiple keys with same email.

### ISSUE THREAD

**Issue by shockoe-hatch** [sobolevn/git-secret#633] opened 2021-01-13 19:03 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. Add two keys with same email associated.
2. Try to use git secret killperson <email>
3. This will not allow you to run this operation

Currently I am also unable to run a `git secret hide` I receive an error that there is a key that has been revoked, expired, or otherwise invalid.  I have tried to remove this key yet I have multiple keys with the same email. So it doesn't allow me to remove stating there are 2 keys found in keyring.

What were you expecting to happen?
Is there a way to specify which key to remove without using email to do this? 

What versions of software are you using?

**`git-secret` path:** (`which git-secret`) …
/usr/local/bin/git-secret
**`git-secret` version:** (`git secret --version`) …
0.3.3
**`git` version:** (`git --version`) …
2.21.1
**Shell type and version:** (`$SHELL --version`) …
zsh 5.7.1
**`gpg` version:** (`gpg --version`) …
2.2.27

**Comment by joshrabinowitz** [comment] 2021-01-13 20:31
Hello @shockoe-hatch 

Thank you very much for this issue report.

I'll look into this and see if I can reproduce. I'll also see if I can a short-term way to fix your issue before we address this in code.

**Comment by joshrabinowitz** [comment] 2021-01-13 21:22
Ok, I've looked into this and this is what I found:

1) If you have a key for an email, let's say 'bobby@example.com', and you `tell` the same email address, _with the same key_ twice, it is _not_ added a second time, even though it appears to be (see #634). You can also see this for yourself using `git secret tell` in  `verbose` mode

2) If you have a key for that email, and you use `git secret tell bobby@example.com` once, _then delete that private/public key from your personal keyring with ` gpg --delete-secret-keys bobby-test@example.com ` and ` gpg --delete-keys bobby-test@example.com `, THEN you create a new key for that email, and THEN you say `git secret tell bobby@example.com` a second time, git-secret WILL add a second key to the git-secret repo's keychain (in .gitsecret/keys) for the `bobby-test@example.com`. Then if you try to use `git secret killperson bobby-test@example.com`, you get the error `git-secret: abort: 2 keys found in gpg keyring for: bobby-test@example.com`, and (with the current code) you cannot use `killperson` with that email address.

3) I think that @shockoe-hatch _actually has_ a ' revoked, expired, or otherwise invalid' key in their git-secret keychain. Because of this, [and _also_ because of  2) mentioned above], git-secret cannot remove and of the keys for that user from the git-secret keychain.

@shockoe-hatch, I think the workaround is to use gpg with --remove-key and with the --homedir option set to your `.gitsecret/keys` dir, so you can remove the offending public keys from your gitsecret repo.

We also need to tighten up error checking and messaging around `tell` and `killperson` to:
* allow killperson to operate if there are multiple keys for a given email (#636)
* improve error messaging if the user `tells` the same email address twice (#635)

Please let us know if you are able to resolve your issue using the gpg `--homedir` option, and if you have any other questions or issues.

**Comment by joshrabinowitz** [comment] 2021-01-13 21:33
also, to your question `Is there a way to specify which key to remove without using email to do this?`

The answer currently is `no`; but see issue #268 where we suggest extending git-secret to let users specify keys by key ids and/or fingerprints.

**Comment by shockoe-hatch** [comment] 2021-01-13 21:59
@joshrabinowitz Thanks for the quick response. Your suggested workaround to use gpg and specifying --homedir to remove expired key worked perfectly thank you!

**Comment by joshrabinowitz** [comment] 2021-01-14 00:15
Glad to hear it @shockoe-hatch , I'll go ahead and close this ticket.

**Closed by joshrabinowitz** 2021-01-14 00:15 UTC

**Comment by arran-nz** [comment] 2021-05-18 14:05
Thanks for the solution @joshrabinowitz ! Here's a quick summary for the one's who land here and want a quick answer.

---
## Remove a duplicate key
If a key is present multiple times, you will receive the following output when using `killperson`

```bash
$ git secret killperson <EMAIL>
git-secret: abort: 3 keys found in gpg keyring for: <EMAIL>
```

To solve this, run the following:

```bash
$ gpg --homedir .gitsecret/keys/ --delete-key <EMAIL>
```
