### ISSUE TITLE
All commands give this exception: .gitsecret folder is ignored. abort.

### ISSUE THREAD

**Issue by Clancey** [sobolevn/git-secret#14] opened 2016-05-09 22:34 UTC
I have a standard .gitignore, if its empty everything works. But when I use the following it completly breaks git secret.
# Autosave files

*~
# build

[Oo]bj/
[Bb]in/
packages/
TestResults/
# globs

Makefile.in
*.DS_Store
*.sln.cache
*.suo
*.cache
*.pidb
*.userprefs
*.usertasks
config.log
config.make
config.status
aclocal.m4
install-sh
autom4te.cache/
*.user
*.tar.gz
tarballs/
test-results/
Thumbs.db
# Mac bundle stuff

*.dmg
*.app
# resharper

__Resharper._
*.Resharper
# dotCover

*.dotCover

**Comment by Clancey** [comment] 2016-05-09 22:37
I think I realized the issue, its the empty lines that causes the issue. If I remove all empty lines it works.

**Comment by sobolevn** [comment] 2016-05-09 23:03
thanks for the feedback. I will try to fix it asap.

**Comment by sobolevn** [comment] 2016-05-10 14:12
@Clancey sorry, but I can not recreate your issue. What's your setup?

OS? bash/zsh/etc?

What have I tried:
1. Did the init process
2. Created `.gitignore` with empty lines and comments
3. Added files, removed them, everything worked

**Comment by Clancey** [comment] 2016-05-10 17:52
OSX, standard bash/terminal. 
I already had a repo with a gitignore and prior commits.
I was unable to do "git secret init"

**Comment by sobolevn** [comment] 2016-05-10 20:41
What's the exact error message?

**Comment by Clancey** [comment] 2016-05-10 20:45
I just tried it on a different repo, and I cannot replicate it anymore.

**Comment by sobolevn** [comment] 2016-05-10 20:47
Well, if you ever find out - let me know. Thanks, anyway!

**Comment by Tensho** [comment] 2016-06-07 07:38
I have the same problem. I don't quite understand why should I commit `.gitsecret`.

**Comment by sobolevn** [comment] 2016-06-07 08:04
`.gitsecret` folder contains all the logic files to make the program work. It actually contains:
1. public keys used for encryption
2. path mappings, which files you want to track (encrypt and decrypt)

So, if this folder is missing the whole app will crash. To prevent this kind of errors, there's a special warning which says that this folder can't be ignored. 

If you find it confusing, I can suggest to change the warning message to be more specific.

**Comment by Tensho** [comment] 2016-06-07 08:38
No, I think it's rather expressive. It's personally my problem, that I haven't understood it properly. I'm not enough fluent with PGP algo and GPG tool, but I thought that we don't need to push pub key, because everyone who should know it from my team is able to retrieve from the some kind of world-wide PKI server, I guess. So the only reason to do in a such way... If you work in closed private network without access to remote public key server.
Thank you very much, so quick response ^_^

**Comment by akonon** [comment] 2017-04-12 00:44
I have the same issue. There's a repo on Ubuntu 16.04 and git secret works well there. When pulled the repo on CentOS7, whatever command I try, I keep getting:

```
error: unknown option `no-index'
usage: git check-ignore [options] pathname...
   or: git check-ignore [options] --stdin < <list-of-paths>

    -q, --quiet           suppress progress reporting
    -v, --verbose         be verbose

    --stdin               read file names from stdin
    -z                    input paths are terminated by a null character

.gitsecret folder is ignored. abort.
```

This happens not only in my old repository. I can't initialize git secret in a new one as well (with the same error).

The package seems to be installed properly

```
$ sudo yum install git-secret
Пакет git-secret-0.2.2-1.noarch уже установлен, и это последняя версия.
Выполнять нечего
```

**Comment by sobolevn** [comment] 2017-04-12 00:45
@akonon it is not the same issue as it seams to me.
Could you please open a new one?

Thanks!

**Comment by TopherGopher** [comment] 2017-09-18 17:01
I was able to replicate (and fix) by following @Clancey's comment https://github.com/sobolevn/git-secret/issues/14#issuecomment-218010655
You can have comments, but you cannot have empty lines.
On OSX using ZSH with a repo and a global gitignore file.

**Comment by sobolevn** [comment] 2017-09-18 20:46
@TopherGopher could you please provide an example?

**Comment by TopherGopher** [comment] 2017-09-19 16:14
This is...bizarre.
I reintroduced whitespace all over the place in both global and local .gitignore files, committed and then could not reproduce.
I have tried with fresh repos, clean branches, nothing.
I have the original error message from the repo

```bash
~/src/cf-scoring-verifier:150645942-scoring-verifier$ git secret init
.gitsecret folder is ignored. abort.
```

But since I cannot reproduce for you...feel free to re-close...
Just...huh.

**Comment by sobolevn** [comment] 2017-09-19 16:16
👻 

Sounds strange, quite sure that is not `git-secret` issue.

**Closed** 2017-09-19 16:15 UTC

**Comment by TopherGopher** [comment] 2017-09-19 16:17
It's just weird that changing the gitignore file worked for the fix, that's why I'm just so...confused.
Which is a normal state for me, so... :-)

**Comment by notjames** [comment] 2018-03-13 00:38
at first glance, this appears to be a bug in `git rev-parse` but I'm still verifying. What I have so far is:

from outside the script, running `strace`, `git rev-parse` is supposed to recursively backward check the path until it finds a directory called `.git`. For some reason, within the script, it checks PWD and then when it finds no `.git` it hard fails. I'm not using symlinks (hard or soft) so why it just fails is not immediately understood.

**Comment by notjames** [comment] 2018-03-13 00:58
I just noticed that this issue is closed and it *may* not be related, though I have a sneaky suspicion it might be if not mildly. Let me know if you want me to create a new issue to track this. Meh, I might just anyway.

**Comment by sobolevn** [comment] 2018-03-13 06:52
@notjames yes, please. open a new one.

**Comment by notjames** [comment] 2018-03-13 07:28
@sobolevn will do.

**Comment by nikolaia** [comment] 2018-05-18 08:13
I had this problem due to CLRF line endings, changing my `.gitignore`-file to have LF line endings made git-secret work as intended. CLRF line endings might be the case for many people working on a repo living on the Windows file system using _Bash for Windows_ or the WSL subsystem.

**Comment by wpcarro** [comment] 2020-08-20 11:06
I'm getting this issue on Linux, but I do have `\n\n` (i.e. 2x newlines) in my `.gitignore`. Should that be problematic? This error and the error message both surprise me.

**Comment by wpcarro** [comment] 2020-08-20 11:22
Even after removing the 2x-newlines, I get the following error:

```
fatal: /home/wpcarro/briefcase/.gitsecret: pathspec magic not supported by this command: 'literal'
git-secret: abort: '/home/wpcarro/briefcase/.gitsecret' is in .gitignore
```

I ran `grep -U "^M" < .gitignore` to find any CRLF newlines, but that appeared empty as I expected since I'm running Linux.

Here's my `.gitignore`:

```gitignore
.vim
./configs/secrets
**/*/.emacs.d/quelpa/**/*
**/*/.emacs.d/elpa/**/*
**/*/.emacs.d/emojis
**/*/.emacs.d/auto-save-list/**/*
**/*/.emacs.d/eshell/
**/*/.emacs.d/var/**/*
**/*/.emacs.d/.cache/**/*
**/*/.emacs.d/request
**/*/.emacs.d/network-security.data
**/*/.emacs.d/smex-items
**/*/.gnupg/random_seed
.netrwhist
Vundle.vim
**/*/.emacs.d/custom.el
**/*/.emacs.d/projectile-bookmarks.eld
**/*/.emacs.d/bookmarks
**/*/transient/history.el
*.hi
*.o
__pycache__
*.class
node_modules/
/configs/.config/fish/config.fish
/configs/.config/fish/fish_variables
/website/blog/public/
/emacs/.emacs.d/tramp
.gitsecret/keys/random_seed
!*.secret
secrets.json
```

This is currently preventing me from using `git-secret` since I need to commit `--no-verify`, which feels like a reckless habit to develop.

Any ideas? How much of this might just be user error?

**Comment by joshrabinowitz** [comment] 2020-08-26 15:27
@wpcarro can you confirm which version of git-secret you are using? That is, what is the output of
    
    git-secret --version

If you're seeing an issue with git-secret, I think it was fixed.

If you're still seeing this issue, please also see the docs on using SECRETS_VERBOSE=1 at https://github.com/sobolevn/git-secret/blob/master/man/man7/git-secret.7.ronn#configuration and see if using `export SECRETS_VERBOSE=1` gives more details on what's going wrong. If you are still seeing this issue after trying with the most recent release of git-secret and using SECRETS_VERBOSE=1, please open a new ticket to track this, the but first reported here  in 2016 has definitely been fixed.
