### ISSUE TITLE
'git secret init' doesn't work on secondary internal drives (mac)

### ISSUE THREAD

**Issue by rakaw** [sobolevn/git-secret#183] opened 2018-06-06 00:28 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. cd /Volumes/SSHD/SSD\ Files/Documents/Documents\ myFolder/Code\ -\ Git/project
2. git secret init

What happens?
-------------
'/Volumes/SSHD/SSD Files/Documents/Documents myFolder/Code - Git/project/.gitsecret/' created.
gawk: cmd. line:3: fatal: cannot open file `/Volumes/SSHD/SSD' for reading (No such file or directory)
cleaning up...

Comments
-------------
- git-secret works on main internal drive (this is my current work-around)
   - ex. "~/Desktop"

What versions of software are you using?
----------------------------------------
**Operating system:** 
- MacOS High Sierra 10.13.5
- Darwin My-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:33:09 PDT 2018; root:xnu-4570.61.1~2/RELEASE_X86_64 x86_64

**`git-secret` path:** /usr/local/bin/git-secret

**`git-secret` version:** 0.2.3

**`git` version:** 2.8.4

**Shell type and version:** version 3.2.57(1)-release (x86_64-apple-darwin17)

**`gpg` version:** gpg 2.2.7

**Comment by rakaw** [comment] 2018-06-06 00:36
Looks like it was just a problem with spaces in directory names

**Comment by sobolevn** [comment] 2018-06-06 07:46
Yeap, closing as duplicate of #135

**Closed by sobolevn** 2018-06-06 07:46 UTC
