### ISSUE TITLE
Issue encrypting a file when some uids are revoked

### ISSUE THREAD

**Issue by pgporada** [sobolevn/git-secret#280] opened 2018-11-28 21:25 UTC
Thanks a lot for this project! I am having a time because past me decided to revoke some uids on a key.

What are the steps to reproduce this issue?
-------------------------------------------
1. `git secret hide`

What happens?
-------------
I try to encrypt a file, but encounter a gpg error due to having revoked uids on my key. Addtionally, the encrypted file does not get created.
```
$ cat secret.txt 
lol cats

$ git secret hide
gpg: error retrieving 'pporada@greenlancer.com' via WKD: No data
gpg: pporada@greenlancer.com: skipped: No data
gpg: /home/phil/test-acles/secret.txt: encryption failed: No data
git-secret: abort: problem encrypting file with gpg: exit code 2: secret.txt

$ ls -al
total 92
drwxrwxr-x   4 phil phil  4096 Nov 28 16:18 .
drwx------ 113 phil phil 40960 Nov 28 16:17 ..
drwxrwxr-x   8 phil phil  4096 Nov 28 16:30 .git
-rw-------   1 phil phil    39 Nov 28 16:18 .gitignore
drwxrwxr-x   4 phil phil  4096 Nov 28 16:18 .gitsecret
-rw-rw-r--   1 phil phil   119 Nov 28 15:26 README.md
-rw-rw-r--   1 phil phil    10 Nov 28 15:27 secret.txt

$ git secret hide -F
gpg: error retrieving 'pporada@greenlancer.com' via WKD: No data
gpg: pporada@greenlancer.com: skipped: No data
gpg: /home/phil/test-acles/secret.txt: encryption failed: No data
git-secret: warning: problem encrypting file with gpg: exit code 2: secret.txt
done. 1 of 1 files are hidden.

$ ls -al
total 92
drwxrwxr-x   4 phil phil  4096 Nov 28 16:18 .
drwx------ 113 phil phil 40960 Nov 28 16:17 ..
drwxrwxr-x   8 phil phil  4096 Nov 28 16:30 .git
-rw-------   1 phil phil    39 Nov 28 16:18 .gitignore
drwxrwxr-x   4 phil phil  4096 Nov 28 16:18 .gitsecret
-rw-rw-r--   1 phil phil   119 Nov 28 15:26 README.md
-rw-rw-r--   1 phil phil    10 Nov 28 15:27 secret.txt

$ git secret list
secret.txt

$ git secret changes
git-secret: abort: cannot find encrypted version of file: secret.txt
```

What were you expecting to happen?
----------------------------------
I am expecting the file to be encrypted, much like if I use the `-F` flag.
```
$ git secret hide
done. 1 of 1 files are hidden.

$ ls -al
total 92
drwxrwxr-x   4 phil phil  4096 Nov 28 16:18 .
drwx------ 113 phil phil 40960 Nov 28 16:17 ..
drwxrwxr-x   8 phil phil  4096 Nov 28 16:30 .git
-rw-------   1 phil phil    39 Nov 28 16:18 .gitignore
drwxrwxr-x   4 phil phil  4096 Nov 28 16:18 .gitsecret
-rw-rw-r--   1 phil phil   119 Nov 28 15:26 README.md
-rw-rw-r--   1 phil phil    10 Nov 28 15:27 secret.txt
-rw-rw-r--   1 phil phil    10 Nov 28 15:27 secret.txt.gpg    <======= This should exist
```

Any logs, error output, etc?
----------------------------

Any other comments?
-------------------
Am I supposed to commit the `.gitsecrets` repo to my public repository too?

```
$ gpg --edit-key C2E660AD9DD4F728
gpg (GnuPG) 2.2.4; Copyright (C) 2017 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Secret key is available.

sec  rsa2048/C2E660AD9DD4F728
     created: 2017-02-19  expires: never       usage: SC  
     trust: unknown       validity: unknown
ssb  rsa2048/ACDB666EF422A116
     created: 2017-02-19  expires: never       usage: E   
[ unknown] (1). Philip Porada <philporada@gmail.com>
[ revoked] (2)  Philip Porada <pporada@greenlancer.com>
[ revoked] (3)  Philip Porada (I work at GreenLancer) <pporada@greenlancer.com>
```

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
```
$ uname -a
Linux laptappy 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**`git-secret` path:** (`which git-secret`) …
```
$ which git-secret
/usr/local/bin/git-secret
```

**`git-secret` version:** (`git secret --version`) …
```
$ git secret --version
0.2.4
```

**`git` version:** (`git --version`) …
```
$ git --version
git version 2.17.1
```

**Shell type and version:** (`$SHELL --version`) …
```
$ $SHELL --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**`gpg` version:** (`gpg --version`) …
```
$ gpg --version
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/phil/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by joshrabinowitz** [comment] 2018-11-29 15:32
Hello, @pgporada 

1) Thank you for the detailed issue report!

2) It looks like you're testing with the master version of git-secret from git, which is helpful because that is the current dev version. (I'm pretty sure the behavior would be a little different with the released version 0.2.4, which also doesn't have the -F option. We won't discuss the released version of 0.2.4 here any more.).

3) If I understand you correctly, you were using a key with the UID pporada@greenlancer.com, and you subsequently revoked that UID using a command something like:

> gpg --edit-key  pporada@greenlancer.com
gpg> revuid pporada@greenlancer.com
(please let me know if this is incorrect)

From my understanding, reuid disassociates the uid `pporada@greenlancer.com` from that key, which means you can't specify that key with that uid any more.

So looking at this issue report, the behavior looks mostly correct. 

As you indicate, if you try to encrypt secrets using an key with a revoked uid you get the error:

> ...
> git-secret: abort: problem encrypting file with gpg: exit code 2: secret.txt

Which seems correct, because I think you can't specify a key using a revoked uid.
* See: https://lists.gnupg.org/pipermail/gnupg-users/2017-February/057601.html

4) When you use `git hide -F`, you're specifically asking it to "force operations to continue even if a file fails to encrypt/decrypt." So in the case of using an key with it's uid revoked, I think it is the correct behavior that `git hide -F`does not create `secret.txt.gpg`

5) The one bug I do see in your output is here:
````
$ git secret hide -F
gpg: error retrieving 'pporada@greenlancer.com' via WKD: No data
gpg: pporada@greenlancer.com: skipped: No data
gpg: /home/phil/test-acles/secret.txt: encryption failed: No data
git-secret: warning: problem encrypting file with gpg: exit code 2: secret.txt
done. 1 of 1 files are hidden.
````

Since the file secret.txt was not successfully hidden, git-secret should report that 0 files were hidden, like so:
> done. 0 of 1 files are hidden.

6) Also, you ask:
>> Am I supposed to commit the .gitsecrets repo to my public repository too?

According the git secret docs <https://github.com/sobolevn/git-secret/blob/master/man/man7/git-secret.7.ronn>, you should check in all contents except the  random_seed  file:

>    all the contents of the .gitsecret/ folder should be checked in, /except/ the random_seed file. In other words, of the files in .gitsecret, only the random_seed file should be mentioned in your .gitignore file.

**Comment by pgporada** [comment] 2018-11-29 18:03
@joshrabinowitz 
1) Nice template for us reporters :)
2) That is correct, I used the latest commit (at the time) from the git repo when I installed git-secret yesterday.
3) Yes, I have pporada@greenlancer.com as a revuid on my personal GPG key. Those commands look familiar which means I probably ran something like that. I do have my main email address as unrevoked and I use it to sign my git commits. I would think that I shouldn't encounter an error? Is there a way to get git-secret to ignore the error?
4) Gotcha, that makes sense.
5) Woot, we got one!
6) Thank you.

**Comment by joshrabinowitz** [comment] 2018-11-29 20:10
You wrote:
>3) Yes, I have pporada@greenlancer.com as a revuid on my personal GPG key. Those commands look familiar which means I probably ran something like that. I do have my main email address as unrevoked and I use it to sign my git commits. I would think that I shouldn't encounter an error? Is there a way to get git-secret to ignore the error?

Git secret specifies gpg keys by email address. 
The problem is that git-secret is referring to your key by the email address that it _was_ associated with it, and after you `revuid`that email address from the key, git-secret can no longer find that key in your gpg keyring. 
I haven't tested it but I believe a solution would be to use `adduid` to add back the association between the email git-secret is using and the gpg key.

**Comment by joshrabinowitz** [comment] 2018-11-30 21:55
Closing as it seems this issue is understood and handled in the current code.

**Closed by joshrabinowitz** 2018-11-30 21:55 UTC
