### ISSUE TITLE
brew's git-secret --version reports 0.2.2, not 0.2.3

### ISSUE THREAD

**Issue by doomsower** [sobolevn/git-secret#137] opened 2018-03-22 12:26 UTC
What are the steps to reproduce this issue?
-------------------------------------------
```bash
 $ brew install git-secret                                                                                                                                                           ==> Downloading https://homebrew.bintray.com/bottles/git-secret-0.2.3.high_sierra.bottle.tar.gz
Already downloaded: /Users/doomsower/Library/Caches/Homebrew/git-secret-0.2.3.high_sierra.bottle.tar.gz
==> Pouring git-secret-0.2.3.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/git-secret/0.2.3: 19 files, 56.3KB

$ git-secret --version                                                                                                                                                              
0.2.2

```

What happens?
-------------
Brew says that it installed v0.2.3, but `git-secret --version` reports 0.2.2
When built from source, correctly reports 0.2.3

What were you expecting to happen?
----------------------------------
`git-secret --version` to report 0.2.3

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) `macOS 10.13.3 (17D47)`

**`git-secret` path:** (`which git-secret`) this is what bug is about...

**`git-secret` version:** (`git secret --version`) this is what bug is about...

**`git` version:** (`git --version`) `git version 2.14.3 (Apple Git-98)`

**Shell type and version:** (`$SHELL --version`) `zsh 5.3 (x86_64-apple-darwin17.0)`

**`gpg` version:** (`gpg --version`) `gpg (GnuPG) 2.2.5 libgcrypt 1.8.2`

**`git` version:** (`git --version`) …

**Comment by joshrabinowitz** [comment] 2018-04-14 20:58
I think this issue is fixed, note mention of 0.2.3 below:

% brew info git-secret
git-secret: stable 0.2.3 (bottled), HEAD
Bash-tool to store the private data inside a git repo
https://sobolevn.github.io/git-secret/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-secret.rb
==> Dependencies
Required: gawk ✔
Recommended: gnupg ✔
==> Options
--without-gnupg
	Build without gnupg support
--HEAD
	Install HEAD version

**Comment by sobolevn** [comment] 2018-04-15 08:45
@joshrabinowitz is right. Closing.

**Comment by joshrabinowitz** [comment] 2018-04-15 13:58
Actually this bug is still correct. While `brew` reports that `0.2.3` is installed, the installed version self-reports `0.2.2`

**Comment by joshrabinowitz** [comment] 2018-04-15 14:02
% brew install git-secret
==> Downloading https://homebrew.bintray.com/bottles/git-secret-0.2.3.high_sierr
==> Pouring git-secret-0.2.3.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/git-secret/0.2.3: 19 files, 56.3KB

% /usr/local/bin/git-secret --version
0.2.2

% grep VERSION /usr/local/bin/git-secret | head -1
GITSECRET_VERSION='0.2.2'

**Comment by sobolevn** [comment] 2018-04-15 19:28
That's strange. We should submit another build to the `homebrew`.

**Comment by notjames** [comment] 2018-04-16 22:59
It's not just home brew. This happens on Linux builds too. 

```

# shellcheck disable=2034
GITSECRET_VERSION='0.2.2'
#!/usr/bin/env bash

```

But I installed 0.2.3 a little over a week ago.

**Comment by joshrabinowitz** [comment] 2018-04-18 14:01
I think the problem is that the 0.2.3 release didn't have the version bumped in src/version.sh , so all installs of the official '0.2.3' release have the wrong version in src/version.sh

Seems like we're moving towards a 0.2.4 release and this is a /wontfix/.

Anyone have pushback on this decision?

**Closed** 2018-04-18 15:17 UTC
Labels: bug, wontfix
