### ISSUE TITLE
Cannot Install git-secret in alpine Docker container

### ISSUE THREAD

**Issue by nylo-andry** [sobolevn/git-secret#802] opened 2022-03-24 20:59 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. `docker run -it alpine sh`
2. Once in the container, I followed the instructions in the Installation page for alpine: https://git-secret.io/installation

What happens?
-------------
During the installation process, even though the public key was downloaded, we get a `permission denied` error.

What were you expecting to happen?
----------------------------------
The installation to be complete

Any logs, error output, etc?
----------------------------
```
...
ERROR: git-secret-0.4.0: Permission denied
...
```

Any other comments?
-------------------
The same process worked earlier today.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) Linux 44c0034d2194 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) None

**`git-secret` version:** (`git secret --version`) It tries to install `0.4.0`

**`git` version:** (`git --version`) `2.34.1`

**Shell type and version:** (`$SHELL --version`) BusyBox v1.34.1

**`gpg` version:** (`gpg --version`)  `2.2.31`

**Comment by kevholmes** [comment] 2022-03-24 21:25
This is a dupe of #801

**Comment by sobolevn** [comment] 2022-03-24 22:04
It fails indeed: https://github.com/sobolevn/git-secret/runs/5683848011?check_suite_focus=true

**Comment by sobolevn** [comment] 2022-03-24 22:06
> JFrog Xray is unavailable. For details, please check Artifactory's log files.

Looks like a problem with JFrog.

**Comment by joshrabinowitz** [comment] 2022-03-25 12:47
This appears resolved: 
https://github.com/sobolevn/git-secret/runs/5685088863?check_suite_focus=true

**Closed by joshrabinowitz** 2022-03-25 12:47 UTC
